import Layout from '../components/Layout'

const EFFECTIVE = '1 August 2026'
const COMPANY = 'CabHouse Agencies Ltd'
const EMAIL = 'customercare@cabhouseagencies.com'
const ADDRESS = 'Off Suneka Asumbi Highway, Kisii, Kenya'

export default function PrivacyPage() {
  return (
    <Layout>
      <div className="max-w-3xl mx-auto px-5 py-16 font-body">
        <p className="text-xs uppercase tracking-[0.2em] font-bold mb-3" style={{ color: 'var(--color-gold)' }}>Legal</p>
        <h1 className="font-display font-black text-3xl mb-2" style={{ letterSpacing: '-0.02em' }}>Privacy Policy</h1>
        <p className="text-slate-500 text-sm mb-10">Effective date: {EFFECTIVE}</p>

        <div className="prose prose-slate max-w-none space-y-8 text-sm leading-relaxed text-slate-700">

          <section>
            <h2 className="font-display font-bold text-lg text-slate-900 mb-3">1. Who we are</h2>
            <p>
              {COMPANY} ("<strong>CabHouse</strong>", "we", "our", or "us") operates cabhouse.site and its associated
              services, including the CabHouse Park, CabHouse Apartments, and CabHouse Water brands.
              We are incorporated in Kenya and our principal place of business is {ADDRESS}.
            </p>
            <p className="mt-2">
              This Privacy Policy explains how we collect, use, store, and protect your personal data when you
              visit our website, make a reservation, or use our services. It is issued in compliance with the
              <strong> Kenya Data Protection Act 2019</strong> (DPA 2019) and, where applicable, the EU General
              Data Protection Regulation (GDPR).
            </p>
            <p className="mt-2">
              Our designated Data Protection Officer can be contacted at <a href={`mailto:${EMAIL}`} className="underline text-slate-900">{EMAIL}</a>.
            </p>
          </section>

          <section>
            <h2 className="font-display font-bold text-lg text-slate-900 mb-3">2. Data we collect</h2>
            <p>We collect information you provide directly and information generated by your use of our services:</p>
            <ul className="mt-3 space-y-1.5 list-disc pl-5">
              <li><strong>Reservation data:</strong> name, phone number, email address, visit date, number of guests, and payment reference details you submit through our booking form.</li>
              <li><strong>Payment data:</strong> M-Pesa transaction codes and the name on the M-Pesa account. We do not collect, store, or process credit or debit card numbers.</li>
              <li><strong>Member portal data:</strong> if you register as a loyalty member, we store your name, phone number, and a PIN of your choosing. We also record coupon transactions linked to your account.</li>
              <li><strong>Communications:</strong> when you contact us via email or WhatsApp, we retain those communications.</li>
              <li><strong>Usage data:</strong> our website does not use analytics cookies or third-party tracking scripts. We do not use Google Analytics, Facebook Pixel, or similar tools.</li>
              <li><strong>Server logs:</strong> our hosting provider may log IP addresses and request timestamps for security and operational purposes.</li>
            </ul>
          </section>

          <section>
            <h2 className="font-display font-bold text-lg text-slate-900 mb-3">3. How we use your data</h2>
            <p>We use the data we collect for the following purposes and legal bases:</p>
            <div className="mt-3 border border-slate-200 rounded-xl overflow-hidden">
              <table className="w-full text-xs">
                <thead className="bg-slate-50">
                  <tr>
                    <th className="text-left px-4 py-3 font-semibold text-slate-600">Purpose</th>
                    <th className="text-left px-4 py-3 font-semibold text-slate-600">Legal basis (DPA 2019 / GDPR)</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100">
                  {[
                    ['Process and confirm your reservation', 'Performance of a contract'],
                    ['Send booking confirmation and payment instructions by email', 'Performance of a contract'],
                    ['Match your M-Pesa payment to your booking', 'Performance of a contract'],
                    ['Manage your loyalty coupon account', 'Performance of a contract / Legitimate interest'],
                    ['Respond to enquiries and support requests', 'Legitimate interest'],
                    ['Comply with legal and regulatory obligations', 'Legal obligation'],
                    ['Detect and prevent fraud or abuse', 'Legitimate interest'],
                  ].map(([p, b]) => (
                    <tr key={p}>
                      <td className="px-4 py-2.5 text-slate-700">{p}</td>
                      <td className="px-4 py-2.5 text-slate-500">{b}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
            <p className="mt-3">
              We do <strong>not</strong> sell your personal data to third parties. We do not use your data for
              automated decision-making or profiling that produces legal or similarly significant effects.
            </p>
          </section>

          <section>
            <h2 className="font-display font-bold text-lg text-slate-900 mb-3">4. Sharing your data</h2>
            <p>We may share your data with:</p>
            <ul className="mt-3 space-y-1.5 list-disc pl-5">
              <li><strong>Service providers</strong> who help us operate our platform (email delivery via Brevo, cloud hosting via Railway). These providers act as data processors under written agreements and may not use your data for their own purposes.</li>
              <li><strong>Staff</strong> at CabHouse who need access to manage your reservation or respond to your enquiry.</li>
              <li><strong>Regulators and law enforcement</strong> where required by Kenyan law or a valid court order.</li>
            </ul>
          </section>

          <section>
            <h2 className="font-display font-bold text-lg text-slate-900 mb-3">5. Data retention</h2>
            <p>
              Reservation records are retained for <strong>seven (7) years</strong> from the date of the reservation
              to satisfy our obligations under Kenyan tax and commercial law.
              Loyalty member accounts are retained for as long as the account is active.
              If you request deletion, we will remove personal identifiers from retained records within 30 days
              unless retention is required by law.
            </p>
          </section>

          <section>
            <h2 className="font-display font-bold text-lg text-slate-900 mb-3">6. Your rights</h2>
            <p>Under the Kenya Data Protection Act 2019 you have the right to:</p>
            <ul className="mt-3 space-y-1.5 list-disc pl-5">
              <li><strong>Access</strong> the personal data we hold about you.</li>
              <li><strong>Correction</strong> of inaccurate or incomplete data.</li>
              <li><strong>Erasure</strong> of data we no longer have a lawful basis to retain.</li>
              <li><strong>Restriction</strong> of processing in certain circumstances.</li>
              <li><strong>Object</strong> to processing based on legitimate interest.</li>
              <li><strong>Data portability</strong> — receive your data in a structured, machine-readable format.</li>
              <li><strong>Withdraw consent</strong> at any time where processing is based on consent (this does not affect the lawfulness of processing before withdrawal).</li>
              <li><strong>Lodge a complaint</strong> with the Office of the Data Protection Commissioner of Kenya (ODPC).</li>
            </ul>
            <p className="mt-3">To exercise any right, email us at <a href={`mailto:${EMAIL}`} className="underline text-slate-900">{EMAIL}</a>. We will respond within 30 days.</p>
          </section>

          <section>
            <h2 className="font-display font-bold text-lg text-slate-900 mb-3">7. Security</h2>
            <p>
              We implement reasonable technical and organisational measures to protect your data against
              unauthorised access, loss, or disclosure. All data is transmitted over HTTPS. Passwords are
              stored using one-way cryptographic hashing. However, no system is completely secure — if you
              believe your data has been compromised, please contact us immediately.
            </p>
          </section>

          <section>
            <h2 className="font-display font-bold text-lg text-slate-900 mb-3">8. Cookies</h2>
            <p>
              This website does not use advertising or analytics cookies. We use a single browser storage
              item to remember that you have acknowledged this cookie notice. No data is shared with third
              parties as a result of cookies.
            </p>
          </section>

          <section>
            <h2 className="font-display font-bold text-lg text-slate-900 mb-3">9. Children</h2>
            <p>
              Our services are not directed at children under the age of 13. We do not knowingly collect
              personal data from children. If you believe a child has submitted data to us, contact us and
              we will delete it.
            </p>
          </section>

          <section>
            <h2 className="font-display font-bold text-lg text-slate-900 mb-3">10. Changes to this policy</h2>
            <p>
              We may update this policy from time to time. Material changes will be posted on this page with
              an updated effective date. Continued use of our services after the effective date constitutes
              acceptance of the updated policy.
            </p>
          </section>

          <section>
            <h2 className="font-display font-bold text-lg text-slate-900 mb-3">11. Contact</h2>
            <p>
              For privacy-related questions or to exercise your rights:
            </p>
            <div className="mt-3 bg-slate-50 rounded-xl p-4 text-sm space-y-1">
              <p><strong>{COMPANY}</strong></p>
              <p>{ADDRESS}</p>
              <p><a href={`mailto:${EMAIL}`} className="underline text-slate-900">{EMAIL}</a></p>
            </div>
          </section>

        </div>
      </div>
    </Layout>
  )
}
